server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/Tabs
spring.datasource.username=antonprilovsky
spring.datasource.password=antonprilovsky

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jackson.serialization.fail-on-empty-beans=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.web.cors.allowed-origins=http://localhost:5173,http://localhost:5174
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
